name: tsacdop_desktop
description: Enjoy podcasts with Tsacdop!

version: 0.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.0.0
  color_thief_flutter: ^1.0.2
  cupertino_icons: ^1.0.2
  crypto: ^3.0.1
  convert: ^3.0.0
  equatable: ^2.0.0
  dart_vlc: ^0.1.6
  effective_dart: ^1.3.1
  flutter_riverpod: ^0.14.0+3
  flutter_linkify: ^3.1.3
  dio: ^4.0.0
  google_fonts: ^2.0.0
  flutter_html: ^0.11.1
  image: ^3.0.1
  path_provider: ^2.0.1
  http_proxy: ^1.1.0
  shared_preferences: ^2.0.5
  sqflite_common_ffi: ^2.0.0
  url_launcher: ^6.0.3
  uuid: ^3.0.4
  desktop_notifications: ^0.6.1
  flutter_gtk:
    git:
      url: https://github.com/stonega/flutter_gtk.git
  line_icons:
    git:
      url: https://github.com/galonsos/line_icons.git
  webfeed:
    git:
      url: https://github.com/stonega/webfeed.git
  resizable_widget: ^1.0.5

dependency_overrides:
  xml: 5.0.0
  http: 0.13.0
  linkify:
    git:
      url: https://github.com/stonega/linkify.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
  uses-material-design: true

flutter_intl:
  enabled: true
  localizely:
    project_id: bde4e9bd-4cb2-449b-9de2-18f231ddb47d
